services:
  - type: web
    name: tickashi-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./todo.db  # Update if using PostgreSQL later
